name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile, test, and package modules
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Compile, test, and package modules
        env:
          MAVEN_OPTS: '-Dorg.slf4j.simpleLogger.showDateTime=true -Djava.wat.headless=true'
        run: ./mvnw --batch-mode --errors --fail-at-end --no-transfer-progress --show-version verify

      - name: Generate coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
